"""Typed helper functions for every INSERT / SELECT the agents and API need.

All functions accept an ``aiosqlite.Connection`` as their first argument.
Timestamps are UTC ISO 8601 strings.  IDs are ULIDs generated by the caller.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import aiosqlite

from pilab import config
from pilab.db.migrate import apply_migrations

log = logging.getLogger(__name__)

Row = dict[str, Any]

SCHEMA_SQL = Path(__file__).parent / "schema.sql"


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _row_factory(cursor: aiosqlite.Cursor, row: tuple) -> Row:
    cols = [d[0] for d in cursor.description]
    return dict(zip(cols, row))


# -------------------------------------------------------------------
# Database lifecycle
# -------------------------------------------------------------------

async def open_db(path: str | None = None) -> aiosqlite.Connection:
    """Open (and optionally initialise) the database."""
    path = path or config.DB_PATH
    db = await aiosqlite.connect(path)
    db.row_factory = _row_factory  # type: ignore[assignment]
    await db.execute(f"PRAGMA busy_timeout = {config.DB_BUSY_TIMEOUT_MS}")
    await db.execute("PRAGMA journal_mode = WAL")
    await db.execute("PRAGMA foreign_keys = ON")

    # Bootstrap schema if tables don't exist
    try:
        await db.execute("SELECT 1 FROM findings LIMIT 1")
    except aiosqlite.OperationalError:
        log.info("Initialising database schema from %s", SCHEMA_SQL)
        await db.executescript(SCHEMA_SQL.read_text())
        await db.commit()

    await apply_migrations(db)
    return db


# -------------------------------------------------------------------
# Findings
# -------------------------------------------------------------------

async def insert_finding(
    db: aiosqlite.Connection,
    *,
    id: str,
    title: str,
    summary: str | None = None,
    source_type: str,
    source_url: str | None = None,
    topic_tags: str | None = None,
    raw_content: str | None = None,
    scout_pi: str | None = None,
    status: str = "scouted",
) -> None:
    await db.execute(
        """INSERT INTO findings
           (id, title, summary, source_type, source_url, topic_tags,
            raw_content, scout_pi, status, discovered_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (id, title, summary, source_type, source_url, topic_tags,
         raw_content, scout_pi, status, _now()),
    )
    await db.commit()


async def get_finding(db: aiosqlite.Connection, finding_id: str) -> Row | None:
    async with db.execute(
        "SELECT * FROM findings WHERE id = ?", (finding_id,)
    ) as cur:
        return await cur.fetchone()


async def list_findings(
    db: aiosqlite.Connection,
    *,
    status: str | None = None,
    topic: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> list[Row]:
    clauses: list[str] = []
    params: list[Any] = []
    if status:
        clauses.append("status = ?")
        params.append(status)
    if topic:
        clauses.append("topic_tags LIKE ?")
        params.append(f"%{topic}%")
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    params += [limit, offset]
    async with db.execute(
        f"SELECT * FROM findings {where} ORDER BY discovered_at DESC LIMIT ? OFFSET ?",
        params,
    ) as cur:
        return await cur.fetchall()


async def update_finding_status(
    db: aiosqlite.Connection, finding_id: str, status: str
) -> None:
    await db.execute(
        "UPDATE findings SET status = ? WHERE id = ?", (status, finding_id)
    )
    await db.commit()


# -------------------------------------------------------------------
# Evaluations
# -------------------------------------------------------------------

async def insert_evaluation(
    db: aiosqlite.Connection,
    *,
    id: str,
    finding_id: str,
    novelty_score: int | None = None,
    pi_feasibility_score: int | None = None,
    feasibility_notes: str | None = None,
    ram_estimate_gb: float | None = None,
    requires_gpu: bool = False,
    verdict: str | None = None,
    verdict_reason: str | None = None,
    evaluated_by: str | None = None,
) -> None:
    await db.execute(
        """INSERT INTO evaluations
           (id, finding_id, novelty_score, pi_feasibility_score,
            feasibility_notes, ram_estimate_gb, requires_gpu,
            verdict, verdict_reason, evaluated_by, evaluated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (id, finding_id, novelty_score, pi_feasibility_score,
         feasibility_notes, ram_estimate_gb, int(requires_gpu),
         verdict, verdict_reason, evaluated_by, _now()),
    )
    await db.commit()


async def get_evaluation_by_finding(
    db: aiosqlite.Connection, finding_id: str
) -> Row | None:
    async with db.execute(
        "SELECT * FROM evaluations WHERE finding_id = ?", (finding_id,)
    ) as cur:
        return await cur.fetchone()


# -------------------------------------------------------------------
# Projects
# -------------------------------------------------------------------

async def insert_project(
    db: aiosqlite.Connection,
    *,
    id: str,
    finding_id: str,
    evaluation_id: str | None = None,
    title: str,
    status: str = "awaiting_approval",
    topic_tags: str | None = None,
) -> None:
    await db.execute(
        """INSERT INTO projects
           (id, finding_id, evaluation_id, title, status, topic_tags)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (id, finding_id, evaluation_id, title, status, topic_tags),
    )
    await db.commit()


async def get_project(db: aiosqlite.Connection, project_id: str) -> Row | None:
    async with db.execute(
        "SELECT * FROM projects WHERE id = ?", (project_id,)
    ) as cur:
        return await cur.fetchone()


async def list_projects(
    db: aiosqlite.Connection,
    *,
    status: str | None = None,
    topic: str | None = None,
) -> list[Row]:
    clauses: list[str] = []
    params: list[Any] = []
    if status:
        clauses.append("status = ?")
        params.append(status)
    if topic:
        clauses.append("topic_tags LIKE ?")
        params.append(f"%{topic}%")
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    async with db.execute(
        f"SELECT * FROM projects {where} ORDER BY approved_at DESC NULLS LAST, id DESC",
        params,
    ) as cur:
        return await cur.fetchall()


async def update_project_status(
    db: aiosqlite.Connection, project_id: str, status: str
) -> None:
    extras = ""
    params: list[Any] = [status]
    if status == "in_progress":
        extras = ", started_at = ?"
        params.append(_now())
    elif status == "completed":
        extras = ", completed_at = ?"
        params.append(_now())
    params.append(project_id)
    await db.execute(
        f"UPDATE projects SET status = ?{extras} WHERE id = ?", params
    )
    await db.commit()


async def approve_project(
    db: aiosqlite.Connection, project_id: str, approved_by: str = "dashboard"
) -> None:
    await db.execute(
        "UPDATE projects SET status = 'approved', approved_by = ?, approved_at = ? WHERE id = ?",
        (approved_by, _now(), project_id),
    )
    await db.commit()


# -------------------------------------------------------------------
# Milestones
# -------------------------------------------------------------------

async def insert_milestone(
    db: aiosqlite.Connection,
    *,
    id: str,
    project_id: str,
    sequence: int,
    title: str,
    description: str | None = None,
    done_condition: str | None = None,
    category: str | None = None,
    estimated_days: int | None = None,
    status: str = "pending",
) -> None:
    await db.execute(
        """INSERT INTO milestones
           (id, project_id, sequence, title, description, done_condition,
            category, estimated_days, status)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (id, project_id, sequence, title, description, done_condition,
         category, estimated_days, status),
    )
    await db.commit()


async def list_milestones(
    db: aiosqlite.Connection, project_id: str
) -> list[Row]:
    async with db.execute(
        "SELECT * FROM milestones WHERE project_id = ? ORDER BY sequence",
        (project_id,),
    ) as cur:
        return await cur.fetchall()


async def update_milestone_status(
    db: aiosqlite.Connection, milestone_id: str, status: str
) -> None:
    extras = ""
    params: list[Any] = [status]
    if status == "completed":
        extras = ", completed_at = ?"
        params.append(_now())
    params.append(milestone_id)
    await db.execute(
        f"UPDATE milestones SET status = ?{extras} WHERE id = ?", params
    )
    await db.commit()


# -------------------------------------------------------------------
# Learnings
# -------------------------------------------------------------------

async def insert_learning(
    db: aiosqlite.Connection,
    *,
    id: str,
    project_id: str,
    milestone_id: str | None = None,
    category: str | None = None,
    note: str,
    agent: str | None = None,
) -> None:
    await db.execute(
        """INSERT INTO learnings
           (id, project_id, milestone_id, category, note, agent, logged_at)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        (id, project_id, milestone_id, category, note, agent, _now()),
    )
    await db.commit()


async def list_learnings(
    db: aiosqlite.Connection, project_id: str
) -> list[Row]:
    async with db.execute(
        "SELECT * FROM learnings WHERE project_id = ? ORDER BY logged_at",
        (project_id,),
    ) as cur:
        return await cur.fetchall()


async def has_learning_for_milestone(
    db: aiosqlite.Connection, milestone_id: str
) -> bool:
    async with db.execute(
        "SELECT 1 FROM learnings WHERE milestone_id = ? LIMIT 1",
        (milestone_id,),
    ) as cur:
        return (await cur.fetchone()) is not None


# -------------------------------------------------------------------
# Rejections
# -------------------------------------------------------------------

async def insert_rejection(
    db: aiosqlite.Connection,
    *,
    id: str,
    finding_id: str,
    evaluation_id: str | None = None,
    reason_code: str | None = None,
    reason_detail: str | None = None,
) -> None:
    await db.execute(
        """INSERT INTO rejections
           (id, finding_id, evaluation_id, reason_code, reason_detail, rejected_at)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (id, finding_id, evaluation_id, reason_code, reason_detail, _now()),
    )
    await db.commit()


async def list_rejections(
    db: aiosqlite.Connection,
    *,
    reason_code: str | None = None,
    limit: int = 50,
) -> list[Row]:
    clauses: list[str] = []
    params: list[Any] = []
    if reason_code:
        clauses.append("reason_code = ?")
        params.append(reason_code)
    where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
    params.append(limit)
    async with db.execute(
        f"SELECT * FROM rejections {where} ORDER BY rejected_at DESC LIMIT ?",
        params,
    ) as cur:
        return await cur.fetchall()


# -------------------------------------------------------------------
# Agent events
# -------------------------------------------------------------------

async def insert_event(
    db: aiosqlite.Connection,
    *,
    id: str,
    agent_name: str,
    event_type: str,
    entity_id: str | None = None,
    message: str | None = None,
) -> None:
    await db.execute(
        """INSERT INTO agent_events
           (id, agent_name, event_type, entity_id, message, occurred_at)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (id, agent_name, event_type, entity_id, message, _now()),
    )
    await db.commit()


async def list_events(
    db: aiosqlite.Connection, *, limit: int = 50
) -> list[Row]:
    async with db.execute(
        "SELECT * FROM agent_events ORDER BY occurred_at DESC LIMIT ?",
        (limit,),
    ) as cur:
        return await cur.fetchall()


async def last_heartbeat(
    db: aiosqlite.Connection, agent_name: str
) -> str | None:
    async with db.execute(
        "SELECT MAX(occurred_at) FROM agent_events WHERE agent_name = ? AND event_type = 'heartbeat'",
        (agent_name,),
    ) as cur:
        row = await cur.fetchone()
        return row["MAX(occurred_at)"] if row else None


# -------------------------------------------------------------------
# Seen URLs
# -------------------------------------------------------------------

async def is_url_seen(db: aiosqlite.Connection, url_hash: str) -> bool:
    async with db.execute(
        "SELECT 1 FROM seen_urls WHERE hash = ?", (url_hash,)
    ) as cur:
        return (await cur.fetchone()) is not None


async def mark_url_seen(db: aiosqlite.Connection, url_hash: str) -> None:
    await db.execute(
        "INSERT OR IGNORE INTO seen_urls (hash, seen_at) VALUES (?, ?)",
        (url_hash, _now()),
    )
    await db.commit()


# -------------------------------------------------------------------
# Job queue
# -------------------------------------------------------------------

async def enqueue_job(
    db: aiosqlite.Connection, *, id: str, finding_id: str
) -> None:
    await db.execute(
        "INSERT INTO job_queue (id, finding_id, status, created_at) VALUES (?, ?, 'pending', ?)",
        (id, finding_id, _now()),
    )
    await db.commit()


async def claim_job(
    db: aiosqlite.Connection, claimed_by: str
) -> Row | None:
    """Claim the oldest pending job.  Returns the job row or None."""
    now = _now()
    async with db.execute(
        "SELECT * FROM job_queue WHERE status = 'pending' ORDER BY created_at LIMIT 1"
    ) as cur:
        job = await cur.fetchone()
    if not job:
        return None
    await db.execute(
        "UPDATE job_queue SET status = 'claimed', claimed_at = ?, claimed_by = ? WHERE id = ?",
        (now, claimed_by, job["id"]),
    )
    await db.commit()
    job["status"] = "claimed"
    job["claimed_at"] = now
    job["claimed_by"] = claimed_by
    return job


async def complete_job(db: aiosqlite.Connection, job_id: str) -> None:
    await db.execute(
        "UPDATE job_queue SET status = 'done' WHERE id = ?", (job_id,)
    )
    await db.commit()


async def fail_job(
    db: aiosqlite.Connection, job_id: str, error_message: str
) -> None:
    await db.execute(
        "UPDATE job_queue SET status = 'error', error_message = ? WHERE id = ?",
        (error_message, job_id),
    )
    await db.commit()


async def reap_stale_jobs(
    db: aiosqlite.Connection, timeout_seconds: int
) -> int:
    """Reset jobs claimed longer than *timeout_seconds* back to pending.
    Returns the number of reaped jobs."""
    cutoff = datetime.now(timezone.utc).timestamp() - timeout_seconds
    # SQLite stores ISO strings; compare lexicographically (works for ISO 8601)
    cutoff_str = datetime.fromtimestamp(cutoff, tz=timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    cursor = await db.execute(
        "UPDATE job_queue SET status = 'pending', claimed_at = NULL, claimed_by = NULL "
        "WHERE status = 'claimed' AND claimed_at < ?",
        (cutoff_str,),
    )
    await db.commit()
    return cursor.rowcount


# -------------------------------------------------------------------
# Stats (for dashboard)
# -------------------------------------------------------------------

async def get_stats(db: aiosqlite.Connection) -> Row:
    stats: Row = {}

    async with db.execute(
        "SELECT status, COUNT(*) as cnt FROM findings GROUP BY status"
    ) as cur:
        for row in await cur.fetchall():
            stats[f"findings_{row['status']}"] = row["cnt"]

    async with db.execute(
        "SELECT status, COUNT(*) as cnt FROM projects GROUP BY status"
    ) as cur:
        for row in await cur.fetchall():
            stats[f"projects_{row['status']}"] = row["cnt"]

    async with db.execute("SELECT COUNT(*) as cnt FROM rejections") as cur:
        row = await cur.fetchone()
        stats["rejections_total"] = row["cnt"] if row else 0

    # Scouted this week (last 7 days)
    week_ago = datetime.now(timezone.utc)
    week_ago_str = week_ago.strftime("%Y-%m-%dT%H:%M:%SZ")
    # Approximate: subtract 7 days worth of seconds
    from datetime import timedelta
    week_ago = datetime.now(timezone.utc) - timedelta(days=7)
    week_ago_str = week_ago.strftime("%Y-%m-%dT%H:%M:%SZ")
    async with db.execute(
        "SELECT COUNT(*) as cnt FROM findings WHERE discovered_at >= ?",
        (week_ago_str,),
    ) as cur:
        row = await cur.fetchone()
        stats["scouted_this_week"] = row["cnt"] if row else 0

    # Last heartbeats per agent
    for agent in ("scout", "evaluator", "planner"):
        stats[f"{agent}_last_heartbeat"] = await last_heartbeat(db, agent)

    return stats


# -------------------------------------------------------------------
# Recent titles (for evaluator context)
# -------------------------------------------------------------------

async def recent_titles(
    db: aiosqlite.Connection, limit: int = 20
) -> list[str]:
    """Return titles of the most recent evaluated findings for novelty context."""
    async with db.execute(
        "SELECT f.title FROM findings f "
        "JOIN evaluations e ON e.finding_id = f.id "
        "ORDER BY e.evaluated_at DESC LIMIT ?",
        (limit,),
    ) as cur:
        rows = await cur.fetchall()
        return [r["title"] for r in rows]
